spring.application.name=backend

spring.datasource.url=jdbc:h2:file:./data/testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://tdobxymtqqnbwpiriwsb.supabase.co/auth/v1
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://tdobxymtqqnbwpiriwsb.supabase.co/auth/v1/keys